
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-04
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-04
pull_requests: [{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"aw-paged-users-front","number":47,"title":"Aw - Paginated Users Frontend #27","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/47"},{"author":{"id":"MDQ6VXNlcjIzNTY0NDU2","is_bot":false,"login":"RyanHung","name":"Ryan Hung"},"headRefName":"rh-frontend-paginate-job-log","number":46,"title":"added jobs frontend components","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/46"},{"author":{"id":"MDQ6VXNlcjIzNTY0NDU2","is_bot":false,"login":"RyanHung","name":"Ryan Hung"},"headRefName":"rh-paginate-job-log","number":44,"title":"Modify /api/jobs/paginated endpoint","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/44"},{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-SectionCSVLine-mutation","number":38,"title":"ca - added SectionCSVLine null test based on GradeHistoryTests.java","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/38"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"aw-paged-users","number":33,"title":"aw-Backend for Paginating Users","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/33"}]
