
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-courses-f25-04
owner: ucsb-cs156-f25
repo_name: proj-courses-f25-04
pull_requests: [{"author":{"id":"U_kgDOCM7m8g","is_bot":false,"login":"ChiranArumugam","name":"Chiran Arumugam"},"headRefName":"ca-refactor-api-enrollment-data-csv","number":31,"title":"CA - refactor api enrollment data csv download to remove testExceptionstring","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/31"},{"author":{"id":"U_kgDOCQ1dXg","is_bot":false,"login":"Max-Changg","name":"Max Chang"},"headRefName":"mc-SectionsTable-eslint-tests","number":29,"title":"Mc sections table eslint tests","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/29"},{"author":{"id":"U_kgDOBtIeXg","is_bot":false,"login":"AJP1012","name":""},"headRefName":"ap-remove-gradehistory-exception","number":24,"title":"ap-Removed eslint exception in GradeHistoryGraph","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/24"},{"author":{"id":"U_kgDOCNnsYw","is_bot":false,"login":"anthonywong461","name":"Anthony Wong"},"headRefName":"aw-restore-title","number":23,"title":"restore title draft","url":"https://github.com/ucsb-cs156-f25/proj-courses-f25-04/pull/23"}]
